// 리얼한 더미 데이터 - 실제 음식 떨이 예시
import { Deal } from './types';
import { Timestamp } from 'firebase/firestore';

// 랜덤 마감 시간 생성 (1~72시간 사이)
const getRandomExpiry = () => {
  const now = new Date();
  const hours = Math.floor(Math.random() * 72) + 1;
  return Timestamp.fromDate(new Date(now.getTime() + hours * 60 * 60 * 1000));
};

// 서울 주요 편의점/마트 위치
const stores = [
  { name: '이마트24 강남점', lat: 37.4979, lon: 127.0276 },
  { name: 'GS25 서초점', lat: 37.4833, lon: 127.0322 },
  { name: 'CU 역삼점', lat: 37.5007, lon: 127.0374 },
  { name: '세븐일레븐 논현점', lat: 37.5104, lon: 127.0220 },
  { name: '이마트24 신사점', lat: 37.5244, lon: 127.0205 },
  { name: 'GS25 삼성점', lat: 37.5133, lon: 127.0554 },
  { name: 'CU 압구정점', lat: 37.5274, lon: 127.0283 },
  { name: '세븐일레븐 청담점', lat: 37.5248, lon: 127.0474 },
];

// 리얼한 음식 더미 데이터
export const dummyFoodDeals: Partial<Deal>[] = [
  // 빵/베이커리
  {
    id: 'dummy_bakery_1',
    title: '크로아상 4개입',
    description: '갓 구운 신선한 크로아상! 오늘만 특가',
    originalPrice: 6800,
    discountedPrice: 4080,
    discountRate: 40,
    category: 'bakery',
    storeName: '이마트24 강남점',
    storeId: 'store_1',
    location: { latitude: 37.4979, longitude: 127.0276, address: '서울 강남구' },
    quantity: 8,
    remainingQuantity: 5,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 234,
    likeCount: 28,
  },
  {
    id: 'dummy_bakery_2',
    title: '베이글 6개 세트',
    description: '다양한 맛의 베이글 모음! 마감 임박',
    originalPrice: 8500,
    discountedPrice: 4250,
    discountRate: 50,
    category: 'bakery',
    storeName: 'GS25 서초점',
    storeId: 'store_2',
    location: { latitude: 37.4833, longitude: 127.0322, address: '서울 서초구' },
    quantity: 5,
    remainingQuantity: 2,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 456,
    likeCount: 52,
  },
  {
    id: 'dummy_bakery_3',
    title: '단팥빵 5개입',
    description: '달콤한 단팥이 가득! 오늘 안에 드세요',
    originalPrice: 5000,
    discountedPrice: 2750,
    discountRate: 45,
    category: 'bakery',
    storeName: 'CU 역삼점',
    storeId: 'store_3',
    location: { latitude: 37.5007, longitude: 127.0374, address: '서울 강남구' },
    quantity: 10,
    remainingQuantity: 7,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 189,
    likeCount: 23,
  },
  // 과자/간식
  {
    id: 'dummy_snacks_1',
    title: '새우깡 대용량',
    description: '국민 과자 새우깡! 대용량으로 더 저렴하게',
    originalPrice: 3800,
    discountedPrice: 2660,
    discountRate: 30,
    category: 'snacks',
    storeName: '세븐일레븐 논현점',
    storeId: 'store_4',
    location: { latitude: 37.5104, longitude: 127.0220, address: '서울 강남구' },
    quantity: 20,
    remainingQuantity: 12,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 567,
    likeCount: 78,
  },
  {
    id: 'dummy_snacks_2',
    title: '허니버터칩 2개입',
    description: '인기 스낵 허니버터칩 묶음 특가!',
    originalPrice: 4600,
    discountedPrice: 2530,
    discountRate: 45,
    category: 'snacks',
    storeName: '이마트24 신사점',
    storeId: 'store_5',
    location: { latitude: 37.5244, longitude: 127.0205, address: '서울 강남구' },
    quantity: 18,
    remainingQuantity: 10,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 892,
    likeCount: 124,
  },
  // 유제품
  {
    id: 'dummy_dairy_1',
    title: '서울우유 2.3L',
    description: '신선한 우유! 유통기한 임박 특가',
    originalPrice: 5800,
    discountedPrice: 4060,
    discountRate: 30,
    category: 'dairy',
    storeName: 'GS25 삼성점',
    storeId: 'store_6',
    location: { latitude: 37.5133, longitude: 127.0554, address: '서울 강남구' },
    quantity: 10,
    remainingQuantity: 4,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 345,
    likeCount: 42,
  },
  {
    id: 'dummy_dairy_2',
    title: '요플레 8개입',
    description: '맛있는 요거트! 오늘만 이 가격',
    originalPrice: 7200,
    discountedPrice: 4320,
    discountRate: 40,
    category: 'dairy',
    storeName: 'CU 압구정점',
    storeId: 'store_7',
    location: { latitude: 37.5274, longitude: 127.0283, address: '서울 강남구' },
    quantity: 8,
    remainingQuantity: 5,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 278,
    likeCount: 35,
  },
  // 냉동식품
  {
    id: 'dummy_frozen_1',
    title: '냉동만두 1kg 2봉',
    description: '푸짐한 만두! 냉동실에 쟁여두세요',
    originalPrice: 15000,
    discountedPrice: 9000,
    discountRate: 40,
    category: 'frozen',
    storeName: '세븐일레븐 청담점',
    storeId: 'store_8',
    location: { latitude: 37.5248, longitude: 127.0474, address: '서울 강남구' },
    quantity: 8,
    remainingQuantity: 3,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 623,
    likeCount: 89,
  },
  {
    id: 'dummy_frozen_2',
    title: '냉동피자 3판',
    description: '간편하게 즐기는 피자! 특가 세일',
    originalPrice: 18000,
    discountedPrice: 9900,
    discountRate: 45,
    category: 'frozen',
    storeName: '이마트24 강남점',
    storeId: 'store_1',
    location: { latitude: 37.4979, longitude: 127.0276, address: '서울 강남구' },
    quantity: 6,
    remainingQuantity: 2,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 1024,
    likeCount: 156,
  },
  // 즉석/간편식
  {
    id: 'dummy_instant_1',
    title: '컵라면 6개입',
    description: '인기 컵라면 모음! 야식으로 딱',
    originalPrice: 4800,
    discountedPrice: 3360,
    discountRate: 30,
    category: 'instant',
    storeName: 'GS25 서초점',
    storeId: 'store_2',
    location: { latitude: 37.4833, longitude: 127.0322, address: '서울 서초구' },
    quantity: 20,
    remainingQuantity: 15,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 445,
    likeCount: 67,
  },
  {
    id: 'dummy_instant_2',
    title: '도시락 3개 세트',
    description: '든든한 한끼! 간편하게 데워드세요',
    originalPrice: 12000,
    discountedPrice: 6000,
    discountRate: 50,
    category: 'instant',
    storeName: 'CU 역삼점',
    storeId: 'store_3',
    location: { latitude: 37.5007, longitude: 127.0374, address: '서울 강남구' },
    quantity: 6,
    remainingQuantity: 1,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 789,
    likeCount: 92,
  },
  // 음료
  {
    id: 'dummy_beverage_1',
    title: '탄산음료 1.5L 6개',
    description: '시원한 탄산음료! 대용량 특가',
    originalPrice: 7200,
    discountedPrice: 4320,
    discountRate: 40,
    category: 'beverage',
    storeName: '세븐일레븐 논현점',
    storeId: 'store_4',
    location: { latitude: 37.5104, longitude: 127.0220, address: '서울 강남구' },
    quantity: 15,
    remainingQuantity: 9,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 334,
    likeCount: 48,
  },
  {
    id: 'dummy_beverage_2',
    title: '커피믹스 100개입',
    description: '달콤한 커피믹스! 사무실 필수템',
    originalPrice: 12000,
    discountedPrice: 7800,
    discountRate: 35,
    category: 'beverage',
    storeName: '이마트24 신사점',
    storeId: 'store_5',
    location: { latitude: 37.5244, longitude: 127.0205, address: '서울 강남구' },
    quantity: 8,
    remainingQuantity: 5,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 512,
    likeCount: 73,
  },
  // 과일
  {
    id: 'dummy_fruit_1',
    title: '사과 10입',
    description: '아삭한 사과! 신선도 보장',
    originalPrice: 15000,
    discountedPrice: 9000,
    discountRate: 40,
    category: 'fruit',
    storeName: 'GS25 삼성점',
    storeId: 'store_6',
    location: { latitude: 37.5133, longitude: 127.0554, address: '서울 강남구' },
    quantity: 8,
    remainingQuantity: 4,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 678,
    likeCount: 95,
  },
  {
    id: 'dummy_fruit_2',
    title: '바나나 1.5kg',
    description: '달콤한 바나나! 아침 식사로 추천',
    originalPrice: 5800,
    discountedPrice: 3770,
    discountRate: 35,
    category: 'fruit',
    storeName: 'CU 압구정점',
    storeId: 'store_7',
    location: { latitude: 37.5274, longitude: 127.0283, address: '서울 강남구' },
    quantity: 15,
    remainingQuantity: 8,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 445,
    likeCount: 62,
  },
  // 채소
  {
    id: 'dummy_vegetable_1',
    title: '양파 3kg',
    description: '신선한 양파! 요리 필수 재료',
    originalPrice: 6000,
    discountedPrice: 3900,
    discountRate: 35,
    category: 'vegetable',
    storeName: '세븐일레븐 청담점',
    storeId: 'store_8',
    location: { latitude: 37.5248, longitude: 127.0474, address: '서울 강남구' },
    quantity: 12,
    remainingQuantity: 7,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 289,
    likeCount: 38,
  },
  {
    id: 'dummy_vegetable_2',
    title: '상추 3단',
    description: '싱싱한 상추! 쌈밥으로 드세요',
    originalPrice: 4500,
    discountedPrice: 2250,
    discountRate: 50,
    category: 'vegetable',
    storeName: '이마트24 강남점',
    storeId: 'store_1',
    location: { latitude: 37.4979, longitude: 127.0276, address: '서울 강남구' },
    quantity: 10,
    remainingQuantity: 3,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 567,
    likeCount: 81,
  },
  // 델리/반찬
  {
    id: 'dummy_deli_1',
    title: '김치 3kg',
    description: '맛있는 배추김치! 집밥이 그리울 때',
    originalPrice: 18000,
    discountedPrice: 10800,
    discountRate: 40,
    category: 'deli',
    storeName: 'GS25 서초점',
    storeId: 'store_2',
    location: { latitude: 37.4833, longitude: 127.0322, address: '서울 서초구' },
    quantity: 10,
    remainingQuantity: 5,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 823,
    likeCount: 118,
  },
  {
    id: 'dummy_deli_2',
    title: '장조림 500g',
    description: '구수한 장조림! 밥도둑',
    originalPrice: 12000,
    discountedPrice: 6600,
    discountRate: 45,
    category: 'deli',
    storeName: 'CU 역삼점',
    storeId: 'store_3',
    location: { latitude: 37.5007, longitude: 127.0374, address: '서울 강남구' },
    quantity: 8,
    remainingQuantity: 4,
    expiryDate: getRandomExpiry(),
    status: 'active',
    viewCount: 456,
    likeCount: 67,
  },
];

// 카테고리별로 필터링하는 헬퍼 함수
export const getDummyDealsByCategory = (category: string): Partial<Deal>[] => {
  if (category === 'all' || category === 'food') {
    return dummyFoodDeals;
  }
  return dummyFoodDeals.filter(deal => deal.category === category);
};

// 인기 순으로 정렬
export const getPopularDummyDeals = (limit: number = 5): Partial<Deal>[] => {
  return [...dummyFoodDeals]
    .sort((a, b) => (b.viewCount || 0) - (a.viewCount || 0))
    .slice(0, limit);
};

// 마감 임박 순으로 정렬
export const getExpiringDummyDeals = (limit: number = 5): Partial<Deal>[] => {
  return [...dummyFoodDeals]
    .sort((a, b) => {
      const aTime = a.expiryDate?.toMillis() || 0;
      const bTime = b.expiryDate?.toMillis() || 0;
      return aTime - bTime;
    })
    .slice(0, limit);
};

